docker_build(
    'linkbee-frontend',
    context='.',
    dockerfile='Dockerfile',
    # target='production',
    target='development',
    entrypoint='npm run start',
    live_update=[
        sync('.', '/usr/src/app'),
    ]
)

k8s_resource(
    'chart-linkbee-frontend',
    # port_forwards='3000:80',
    port_forwards='3000:3000',
    # labels=['frontend']
)

# k8s_resource(
#     objects=['linkbee-linkbee-frontend:configmap'],
#     labels=['frontend']
# )