linkbee-backend:
  ingress:
  enabled: true
  className: "private"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.dashboard.dani.rip
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: api.dashboard.dani.rip
     hosts:
       - api.dashboard.dani.rip
linkbee-frontend:
  environment:
    APP_HTTP_API: "https://api.dashboard.dani.rip/graphql"
    APP_WS_API: "wss://api.dashboard.dani.rip/graphql"
  ingress:
    enabled: true
    className: "private"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: dashboard.dani.rip
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
    - secretName: dashboard.dani.rip
      hosts:
        - dashboard.dani.rip