apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
data:
  config.js: |
    window._env_ = {
      {{- range $k, $v := .Values.environment }}
      {{ $k}}: "{{ $v }}",
      {{- end }}
    }
